/** Domain activity `entityType` for payroll runs */
export const PAYROLL_ENTITY_TYPE = "Payroll";

export const PAYROLL_TIMELINE = {
  CREATED: "PAYROLL_CREATED",
  REVIEWED: "PAYROLL_REVIEWED",
  APPROVED: "PAYROLL_APPROVED",
  LOCKED: "PAYROLL_LOCKED",
  PDF_GENERATED: "PAYROLL_PDF_GENERATED",
  PAYROLL_ATK_GENERATED: "PAYROLL_ATK_GENERATED",
  PAYROLL_ATK_DOWNLOADED: "PAYROLL_ATK_DOWNLOADED",
  PAYROLL_ATK_REGENERATED: "PAYROLL_ATK_REGENERATED",
  PAYROLL_ATK_ARCHIVED: "PAYROLL_ATK_ARCHIVED",
  ARCHIVED: "PAYROLL_ARCHIVED",
  RECALCULATED: "PAYROLL_RECALCULATED",
} as const;
